baseURL = "http://soundscapes.ajs.at"
languageCode = "de"
DefaultContentLanguage = "de"
title = "Grazer Soundscapes 2020"

# Theme
theme = "devfest-theme-hugo"

# Params

enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

#googleAnalytics = "UA-37717223-8"

[params]
    title = "Grazer Soundscapes 2020"
    headline = "GRAZER SOUNDSCAPES"
    date = "2020"
    description = "Sie finden es spannend, den Geräuschen Ihrer Umgebung zu lauschen? Und wie oft haben Sie schon gedacht: Das würde ich gerne einmal aufnehmen und anderen Menschen vorspielen – aber wussten nicht so genau, wie und mit welchen Gerätschaften Sie das anstellen können?"
    images = ["/images/social-share.jpg"]
    email = "soundscapes2020@helsinki.at"
    keywords = "soundscapes geräusche radio helsinki aufnahmen grätzl graz"
    copyright = "CC BY Radio Helsinki<br>Freies Radio Graz"
    #cfpUrl = "https://conference-hall.io/public/event/HJRThubF4uYPkb7jSUxi"
    #subscriptionUrl = "http://eepurl.com/dps1j5"
    appleTouchIcon = "/apple-touch-icon.png"
    favicon32 = "/favicon-32x32.png"
    favicon16 = "/favicon-16x16.png"
    manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#673ab7"
    #googleWebmasterKey = "BcIJYWDHoblML5DO66_b1BGBne9J_7Oq3GjC5SDCKK8"

[params.logos]
    jumbo = "/images/logos/soundscapes_startpage.png"
    header = "/images/logos/soundscapes_color_small.png"
    footerleft = "/images/logos/soundscapes_bw.png"
    footermid = "/images/logos/radio_helsinki_bar_black-white.png"
    footerbiglogo = "/images/logos/graz-kulturjahr2020-logo.png"
    footerbiglogoUrl = ""
[menu]
[[menu.main]]
    identifier = "cba"
    name = "Sendungen"
    url = "https://cba.fro.at/series/grazer-soundscapes"
    weight = 200
    external = true

[languages]
[languages.de]
    weight = 1
    languageName = "de"

[languages.en]
    weight = 2
    languageName = "gb"

#[languages.fr]
#    weight = 3
#    languageName = "fr"

#[languages.fr.params]
#    description = "Le DevFest, ou 'Developers Festival', est une conférence technique destinée aux développeurs. Elle s'adresse aussi bien aux étudiants, aux professionnels ou tout simplement aux curieux technophiles."

[taxonomies]
  tag = "tags"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
